import pyphonetics

rs = pyphonetics.RefinedSoundex()
metaphone = pyphonetics.Metaphone()
soundex = pyphonetics.Soundex()
fuzzy_soundex = pyphonetics.FuzzySoundex()


# Phonetic representation is generated by pyphonetics.RefinedSoundex()
def refinedSoundexRep(word):
    return rs.phonetics(word)


# Generate metaphone representations for words. See https://en.wikipedia.org/wiki/Metaphone
def metaPhoneRep(wordString):
    return metaphone.phonetics(wordString)


# Generate fuzzy soundex representation for words. See: Holmes, David and M. Catherine McCabe. "Improving Precision
# and Recall for Soundex Retrieval."
# http://web.archive.org/web/20100629121128/http://www.ir.iit.edu/publications/downloads/IEEESoundexV5.pdf
def fuzzySoundexRep(wordString):
    return fuzzy_soundex.phonetics(wordString)


# Generate soundex representation for words. See: https://en.wikipedia.org/wiki/Soundex
def soundexRep(wordString):
    return soundex.phonetics(wordString)
